### ISSUE TITLE
errors on anything other than nixos and ubuntu.

### ISSUE THREAD

**Issue by vimtoe** [numtide/system-manager#51] opened 2023-11-06 22:35 UTC
**Describe the bug**
errors on anything other than nixos and ubuntu.

**To Reproduce**
try running on any distro other than nixos or ubuntu.

**Expected behavior**
for it to be able to work on other distros.

**System information**
Alpine linux, Void linux, Gentoo. All on latest stable nix.

**Additional context**
The README opening paragraph states "on any linux distro" yet this fails if you are not on nixos or ubuntu?
Is there a reason for the failure? my config is just writing a file to /etc - no services (I do not use systemd).
Also, the paragraph states "for non-nixos systems" yet the above failure states that nixos is supported?

**Comment by aanderse** [comment] 2023-11-07 03:32
NixOS has a hard retirement on `systemd` so this project does as well. Can you explain in more detail?

The documentation could be updated to say "on any `systemd` based distro" which might help. Keep in mind this project is still in it's infancy as well and likely only Ubuntu and NixOS are actively tested at this point.

**Comment by vimtoe** [comment] 2023-11-08 16:57
> can you explain in more detail?
Just as `home-manager` configures a home environment, `system-manager` should configure a system environment.
`home-manager` does not depend on `systemd` - it only relies on `systemd` for starting services, everything (apart from services) is useable from any linux distro.
I was expecting the same here, `systemd` is only needed for starting services - but writing configs (that does not need `systemd`) should work fine from any linux distro.
also, on systems like Void Linux (that uses `runit` for services) simply creating a symlink in `/etc/runit/runsvdir/default/{{SERVICE}}` enables a service, which means that you can support all distros using `runit

**Comment by aanderse** [comment] 2023-11-10 12:12
> 2\. but it doesnt need to be that way.

I'm not exactly sure how to respond to that. The approach taken in developing `system-manager` suits the business needs of numtide. If you have different ideas you'd like to see come a reality I guess I'll quote their [commerical offering](https://github.com/numtide/system-manager#commercial-support):

> Looking for help or customization?
>
> Get in touch with Numtide to get a quote. We make it easy for companies to work with Open Source projects: https://numtide.com/contact

:man_shrugging:

**Comment by a-h** [comment] 2023-11-24 17:25
I just tried it out on Rocky Linux 8, to see if the issue was simply that `systemd` was required (since one of my target environments uses Rocky Linux as a base), but got the same error:

```
[2023-11-24T17:12:40Z INFO  system_manager::activate] Activating system-manager profile: /nix/store/kmvnagfk1xp7rrijv3idivrzbpd85368-system-manager
[2023-11-24T17:12:40Z INFO  system_manager::activate] Running pre-activation assertions...
Evaluating pre-activation assertion osVersion...

This OS is not currently supported.
Supported OSs are: nixos, ubuntu
Pre-activation assertion osVersion failed.
See the output above for more details.
[2023-11-24T17:12:40Z ERROR system_manager] Failure in pre-activation assertions.
⭐ ⚠️ [activate] [WARN] De-activating due to error
error: no profile version older than the current (1) exists
⭐ ❌ [activate] [ERROR] There was an error de-activating after an error was encountered: The rollback resulted in a bad exit code: Some(1)
🚀 ❌ [deploy] [ERROR] Activating over SSH resulted in a bad exit code: Some(1)
🚀 ℹ️ [deploy] [INFO] Revoking previous deploys
🚀 ❌ [deploy] [ERROR] Deployment failed, rolled back to previous generation
xc: exit status 1
```

However, looking at the code, I could see there's a config setting at https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/nix/modules/default.nix#L146

So I was able to set it in the module.

```nix
# system-manager module.
{ lib, pkgs, app, ... }:

{
  config = {
    nixpkgs.hostPlatform = "x86_64-linux";

    system-manager.allowAnyDistro = true;

    # System level dependencies can be added here.
    environment = {
      systemPackages = [
        #pkgs.ripgrep
        #pkgs.fd
        #pkgs.hello
      ];
    };

    systemd.services = {
      example-go-project = {
        enable = true;
        serviceConfig = {
          Type = "simple";
        };
        wantedBy = [ "system-manager.target" ];
        script = ''
          ${lib.getBin app}/bin/example-go-project
        '';
      };
    };
  };
}
```

**Comment by a-h** [comment] 2023-11-24 18:06
Ah, when I ran it again, and read more carefully, I spotted the ERROR output.

```
2023-11-24T17:53:03Z INFO  system_manager::activate] Activating system-manager profile: /nix/store/3q02srg2ayz7gqa20jf3xz1hv2s4iqmf-system-manager
[2023-11-24T17:53:03Z INFO  system_manager::activate] Running pre-activation assertions...
All pre-activation assertions succeeded.
[2023-11-24T17:53:03Z INFO  system_manager::activate] Activating etc files...
[2023-11-24T17:53:03Z INFO  system_manager::activate::etc_files] Reading etc file definitions...
[2023-11-24T17:53:03Z INFO  system_manager::activate::etc_files] Creating /etc entries in /etc
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/.system-manager-static -> /nix/store/mqzfg6wyz0gb5bkflcg2xm3hs4hiza33-etc-static-env
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/default.target.wants/system-manager.target -> ./../../../.system-manager-static/systemd/system/default.target.wants/system-manager.target
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/example-go-project.service -> ./../../.system-manager-static/systemd/system/example-go-project.service
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager-path.service -> ./../../.system-manager-static/systemd/system/system-manager-path.service
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target -> ./../../.system-manager-static/systemd/system/system-manager.target
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/example-go-project.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/example-go-project.service
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/system-manager-path.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/system-manager-path.service
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/profile.d/system-manager-path.sh -> ./../.system-manager-static/profile.d/system-manager-path.sh
[2023-11-24T17:53:03Z INFO  system_manager] Creating symlink: /etc/tmpfiles.d/00-system-manager.conf -> ./../.system-manager-static/tmpfiles.d/00-system-manager.conf
[2023-11-24T17:53:03Z INFO  system_manager::activate::etc_files] Done
[2023-11-24T17:53:03Z INFO  system_manager::activate] Activating tmp files...
[2023-11-24T17:53:03Z INFO  system_manager::activate] Activating systemd services...
[2023-11-24T17:53:03Z INFO  system_manager::activate::services] Reading new service definitions...
[2023-11-24T17:53:03Z INFO  system_manager::activate::services] Reloading the systemd daemon...
[2023-11-24T17:53:03Z ERROR system_manager::activate::services] Service system-manager.target: error starting, please consult the logs
[2023-11-24T17:53:03Z ERROR system_manager::activate::services] Unit system-manager.target not found.
[2023-11-24T17:53:03Z INFO  system_manager::activate::services] Done
[2023-11-24T17:53:03Z INFO  system_manager::activate] Writing state info into file: /var/lib/system-manager/state/system-manager-state.json
⭐ ℹ️ [activate] [INFO] Activation succeeded!                                                                                                                                  
⭐ ℹ️ [activate] [INFO] Magic rollback is enabled, setting up confirmation hook...                                                                                             
👀 ℹ️ [wait] [INFO] Found canary file, done waiting!                                                                                                                           
⭐ ℹ️ [activate] [INFO] Waiting for confirmation event...                                                                                                                      
🚀 ℹ️ [deploy] [INFO] Success activating, attempting to confirm activation                                                                                                     
🚀 ℹ️ [deploy] [INFO] Deployment confirmed.      
```

The log lines in question are:

```
[2023-11-24T17:53:03Z INFO  system_manager::activate::services] Reloading the systemd daemon...
[2023-11-24T17:53:03Z ERROR system_manager::activate::services] Service system-manager.target: error starting, please consult the logs
[2023-11-24T17:53:03Z ERROR system_manager::activate::services] Unit system-manager.target not found.
```

The text "error starting: please consult the logs" comes from https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/src/activate/services.rs#L279C1-L281 and the next line produces the log "system-manager.target not found".

SSH-ing onto my box, and running `cat /etc/systemd/system/system-manager.target`, I can see an empty unit file? But not sure why...

```
[Unit]

```

**Comment by a-h** [comment] 2023-11-24 18:15
Reading further... I can see an attempt to use it here.

https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/src/activate/services.rs#L93

I think the problem is somewhere in the `activate` function, but don't know where.

**Comment by a-h** [comment] 2023-11-27 12:06
I can see that `nix check` in this repo runs a test: https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/flake.nix#L251-L255

It imports the list of Ubuntu images here: https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/test/nix/modules/default.nix#L7-L8

And it messes about downloading them here: https://github.com/numtide/system-manager/blob/17ce0ccb118d8c2de625ecf90e46995734e37684/nix/lib.nix#L168

Since it's quite complicated, I built a test rig using `lima` to start virtual machines, Lima can run Ubuntu or Rocky, and it looks a lot simpler (to me) than the existing test setup.

## Testing with Ubuntu

To compare with my Rocky setup, here's my output from setting up on Ubuntu using Lima.

```
warning: Git tree '/home/adrian-hesketh/github.com/a-h/nix-airgapped-vm' is dirty
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[nix-airgapped-vm.system]
user = "adrian-hesketh"
ssh_user = "adrian-hesketh"
path = "/nix/store/8p0j8a9l13gx5ib4jy6q4qsaginmgjs0-activatable-system-manager"
hostname = "lima-nix-airgapped-vm"
ssh_opts = ["-F", "/home/adrian-hesketh/.lima/nix-airgapped-vm/ssh.config"]

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
⭐ ℹ️ [activate] [INFO] Activating profile
👀 ℹ️ [wait] [INFO] Waiting for confirmation event...
sudo: unable to resolve host lima-nix-airgapped-vm: Temporary failure in name resolution
[2023-11-27T10:46:04Z INFO  system_manager::activate] Activating system-manager profile: /nix/store/3q02srg2ayz7gqa20jf3xz1hv2s4iqmf-system-manager
[2023-11-27T10:46:04Z INFO  system_manager::activate] Running pre-activation assertions...
All pre-activation assertions succeeded.
[2023-11-27T10:46:04Z INFO  system_manager::activate] Activating etc files...
[2023-11-27T10:46:04Z INFO  system_manager::activate::etc_files] Reading etc file definitions...
[2023-11-27T10:46:04Z INFO  system_manager::activate::etc_files] Creating /etc entries in /etc
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/.system-manager-static -> /nix/store/mqzfg6wyz0gb5bkflcg2xm3hs4hiza33-etc-static-env
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/tmpfiles.d/00-system-manager.conf -> ./../.system-manager-static/tmpfiles.d/00-system-manager.conf
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/example-go-project.service -> ./../../.system-manager-static/systemd/system/example-go-project.service
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/default.target.wants/system-manager.target -> ./../../../.system-manager-static/systemd/system/default.target.wants/system-manager.target
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target -> ./../../.system-manager-static/systemd/system/system-manager.target
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/example-go-project.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/example-go-project.service
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/system-manager-path.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/system-manager-path.service
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager-path.service -> ./../../.system-manager-static/systemd/system/system-manager-path.service
[2023-11-27T10:46:04Z INFO  system_manager] Creating symlink: /etc/profile.d/system-manager-path.sh -> ./../.system-manager-static/profile.d/system-manager-path.sh
[2023-11-27T10:46:04Z INFO  system_manager::activate::etc_files] Done
[2023-11-27T10:46:04Z INFO  system_manager::activate] Activating tmp files...
[2023-11-27T10:46:04Z INFO  system_manager::activate] Activating systemd services...
[2023-11-27T10:46:04Z INFO  system_manager::activate::services] Reading new service definitions...
[2023-11-27T10:46:04Z INFO  system_manager::activate::services] Reloading the systemd daemon...
[2023-11-27T10:46:04Z INFO  system_manager::systemd] Waiting for jobs to finish...
[2023-11-27T10:46:04Z INFO  system_manager::systemd] All jobs finished.
[2023-11-27T10:46:04Z INFO  system_manager::activate::services] Done
[2023-11-27T10:46:04Z INFO  system_manager::activate] Writing state info into file: /var/lib/system-manager/state/system-manager-state.json
⭐ ℹ️ [activate] [INFO] Activation succeeded!
⭐ ℹ️ [activate] [INFO] Magic rollback is enabled, setting up confirmation hook...
👀 ℹ️ [wait] [INFO] Found canary file, done waiting!
⭐ ℹ️ [activate] [INFO] Waiting for confirmation event...
🚀 ℹ️ [deploy] [INFO] Success activating, attempting to confirm activation
🚀 ℹ️ [deploy] [INFO] Deployment confirmed.
```

With this running, I can `curl localhost:8080`, and see my app running.

I can see that the `system-manager.target` file is the same as it was on Rocky, so that's not the problem:

```
adrian-hesketh@lima-nix-airgapped-vm:~$ cat /etc/systemd/system/system-manager.target
[Unit]
```

I can see the Go project is running.

```
adrian-hesketh@lima-nix-airgapped-vm:~$ systemctl list-unit-files example-go-project.service
UNIT FILE                  STATE   PRESET 
example-go-project.service enabled enabled

1 unit files listed.
```

I can see that the `system-manager` unit is started:

```
adrian-hesketh@lima-nix-airgapped-vm:~$ systemctl list-unit-files system-manager*
UNIT FILE                   STATE   PRESET 
system-manager-path.service enabled enabled
system-manager.target       enabled enabled

2 unit files listed.
```

## Rocky

Running the test again with Rocky...

```
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[nix-airgapped-vm.system]
user = "adrian-hesketh"
ssh_user = "adrian-hesketh"
path = "/nix/store/8p0j8a9l13gx5ib4jy6q4qsaginmgjs0-activatable-system-manager"
hostname = "lima-nix-airgapped-vm"
ssh_opts = ["-F", "/home/adrian-hesketh/.lima/nix-airgapped-vm/ssh.config"]

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `nix-airgapped-vm`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
⭐ ℹ️ [activate] [INFO] Activating profile
👀 ℹ️ [wait] [INFO] Waiting for confirmation event...
[2023-11-27T11:05:22Z INFO  system_manager::activate] Activating system-manager profile: /nix/store/3q02srg2ayz7gqa20jf3xz1hv2s4iqmf-system-manager
[2023-11-27T11:05:22Z INFO  system_manager::activate] Running pre-activation assertions...
All pre-activation assertions succeeded.
[2023-11-27T11:05:22Z INFO  system_manager::activate] Activating etc files...
[2023-11-27T11:05:22Z INFO  system_manager::activate::etc_files] Reading etc file definitions...
[2023-11-27T11:05:22Z INFO  system_manager::activate::etc_files] Creating /etc entries in /etc
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/.system-manager-static -> /nix/store/mqzfg6wyz0gb5bkflcg2xm3hs4hiza33-etc-static-env
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/default.target.wants/system-manager.target -> ./../../../.system-manager-static/systemd/system/default.target.wants/system-manager.target
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/example-go-project.service -> ./../../.system-manager-static/systemd/system/example-go-project.service
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager-path.service -> ./../../.system-manager-static/systemd/system/system-manager-path.service
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target -> ./../../.system-manager-static/systemd/system/system-manager.target
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/example-go-project.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/example-go-project.service
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/systemd/system/system-manager.target.wants/system-manager-path.service -> ./../../../.system-manager-static/systemd/system/system-manager.target.wants/system-manager-path.service
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/profile.d/system-manager-path.sh -> ./../.system-manager-static/profile.d/system-manager-path.sh
[2023-11-27T11:05:22Z INFO  system_manager] Creating symlink: /etc/tmpfiles.d/00-system-manager.conf -> ./../.system-manager-static/tmpfiles.d/00-system-manager.conf
[2023-11-27T11:05:22Z INFO  system_manager::activate::etc_files] Done
[2023-11-27T11:05:22Z INFO  system_manager::activate] Activating tmp files...
[2023-11-27T11:05:22Z INFO  system_manager::activate] Activating systemd services...
[2023-11-27T11:05:22Z INFO  system_manager::activate::services] Reading new service definitions...
[2023-11-27T11:05:22Z INFO  system_manager::activate::services] Reloading the systemd daemon...
[2023-11-27T11:05:22Z ERROR system_manager::activate::services] Service system-manager.target: error starting, please consult the logs
[2023-11-27T11:05:22Z ERROR system_manager::activate::services] Unit system-manager.target not found.
[2023-11-27T11:05:22Z INFO  system_manager::activate::services] Done
[2023-11-27T11:05:22Z INFO  system_manager::activate] Writing state info into file: /var/lib/system-manager/state/system-manager-state.json
⭐ ℹ️ [activate] [INFO] Activation succeeded!
⭐ ℹ️ [activate] [INFO] Magic rollback is enabled, setting up confirmation hook...
👀 ℹ️ [wait] [INFO] Found canary file, done waiting!
⭐ ℹ️ [activate] [INFO] Waiting for confirmation event...
🚀 ℹ️ [deploy] [INFO] Success activating, attempting to confirm activation
🚀 ℹ️ [deploy] [INFO] Deployment confirmed.
```

OK, so it failed again...

```
[adrian-hesketh@lima-nix-airgapped-vm ~]$ systemctl list-unit-files system-manager*
UNIT FILE                   STATE
system-manager-path.service bad  
system-manager.target       bad  

2 unit files listed.
```

The file is there...

```
[adrian-hesketh@lima-nix-airgapped-vm ~]$ readlink -f /etc/systemd/system/system-manager-path.service 
/nix/store/vav07d8slnk75r4gy5nsir4ianj36g0r-unit-system-manager-path.service/system-manager-path.service
```

But enabling it fails with Access Denied.

```
[adrian-hesketh@lima-nix-airgapped-vm ~]$ sudo systemctl enable system-manager-path
Failed to enable unit: Access denied
```

However, disabling SELinux makes it work OK.

```
[adrian-hesketh@lima-nix-airgapped-vm ~]$ sudo setenforce 0
[adrian-hesketh@lima-nix-airgapped-vm ~]$ sudo systemctl daemon-reload
[adrian-hesketh@lima-nix-airgapped-vm ~]$ systemctl list-unit-files system-manager*
UNIT FILE                   STATE  
system-manager-path.service enabled
system-manager.target       enabled
```

So... it's an SELinux thing. With that knowledge, I could recreate the VM and look at the SELinux audit log using `audit2allow` as per https://opensource.com/article/18/7/sysadmin-guide-selinux

By repeatedly attempting to start the units, and then running `audit2allow -a -M allow-system-manager`, I got a `te` file out that looks like this:

```
module allow-system-manager 1.0;

require {
        type default_t;
        type tmpfs_t;
        type ifconfig_t;
        type init_t;
        class cap_userns net_admin;
        class lnk_file read;
        class file { execute execute_no_trans map open read };
}

#============= ifconfig_t ==============

#!!!! This avc is allowed in the current policy
allow ifconfig_t self:cap_userns net_admin;

#!!!! This avc is allowed in the current policy
allow ifconfig_t tmpfs_t:lnk_file read;

#============= init_t ==============

#!!!! This avc can be allowed using the boolean 'domain_can_mmap_files'
allow init_t default_t:file map;

#!!!! This avc is allowed in the current policy
allow init_t default_t:file { execute execute_no_trans open read };

#!!!! This avc is allowed in the current policy
allow init_t default_t:lnk_file read;
```

Then as part of the Nix installation step, I ran this to build, compile, and install the SELinux module.

```
set -e -x
sudo mkdir /selinux-modules
sudo cp ./dependencies/allow-system-manager.te /selinux-modules
sudo checkmodule -M -m -o /selinux-modules/allow-system-manager.mod /selinux-modules/allow-system-manager.te 
sudo semodule_package -o /selinux-modules/allow-system-manager.pp -m /selinux-modules/allow-system-manager.mod 
sudo semodule -i /selinux-modules/allow-system-manager.pp
```

## Summary

* The current testing process of system-manager could be expanded to Rocky Linux by using Lima to potentially handle both Ubuntu and other distros.
  * I have scripts for this, and am happy to demonstrate over a Google meet or something, and potentially implement the testing.
  * Is this something the maintainers want?
* I don't know if the fact that system-manager doesn't work with SELinux means that:
  * It's a problem with the determinate systems Nix installer I used to install Nix (it does *something* with SELinux on install) - maybe it needs to grant additional permissions.
  * It's an issue with system-manager, in that it didn't really report back that it failed, and in addition, should really setup the appropriate SELinux modules.
  * It's my issue to deal with, because that's SELinux.

**Comment by R-VdP** [comment] 2023-11-27 12:25
Thanks for all the effort put into this!

I'm not surprised that you run into issues with SELinux, since AFAIK SELinux in enforcing mode is designed to stop stuff from working when it's not explicitly white-listed. So for sure when you're running SELinux you will need to take additional steps to get stuff to work.

I don't know about lima, I'd have to look into it. Can we run it as part of a nix build? Is it reproducible?

I am definitely interested in adding test cases for other distros, but only if you are also interested in maintaining support for those distros. I cannot personally commit to this since I don't have the bandwidth, and I don't want to add extra tests if no one will fix them when they start failing.

Is that something that you would potentially be interested in?

**Comment by a-h** [comment] 2023-11-27 12:53
I don't think I can commit to supporting other distros over the long term. I'm a consultant and am only likely to be working on this project for a year, and I already maintain a popular open source side project. I wouldn't choose to use Rocky Linux myself, it's another team's choice that I have to live with.

For more info on Lima, it's included in nixpkgs, but I haven't used it from Nix. You can see my testing workflow and repo at https://github.com/a-h/nix-airgapped-vm

The project demonstrates:

* Starting a VM with Lima (the template sets that it's Rocky Linux, remove that flag and you get Ubuntu)
* Disabling outbound Internet access on it
* Installing Nix offline with the determinate systems installer
* Using a custom Flake registry JSON file to stop Nix constantly trying to download nixpkgs
* Copying nixpkgs projects from the local machine to the VM, and running them there
* Copying the build environment of a local Go project over to the VM, and running it there
* Bundling a Go project, and its build closure as a Docker container
* Creating an SBOM for the project
* Using deploy-rs and system-manager to deploy the Go project to the VM

I migrated from Multipass in https://github.com/a-h/nix-airgapped-vm/commit/a428c97050712278db0b227098459568e0ff3e4e just so that I could test on other Linux distributions.

I don't know that it's any better than what you're doing (likely, it isn't), but I was familiar with it, and it's very easy to debug and get a shell etc.

**Comment by a-h** [comment] 2023-11-27 15:07
Since it's so easy with my test setup, I was able to test it with Fedora 38, and with the SELinux tweaks I made for Rocky above, it also worked well. (I also tested without the SELinux policy, and it didn't work there).

**Comment by r-vdp** [comment] 2024-04-21 22:26
I will close this issue as things are working as intended. Feel free to open PRs to support more distros though.

**Closed by r-vdp** 2024-04-21 22:26 UTC
Labels: bug
